name: Build
on: 
  push:
    paths:
    - '**.ino'
    - '**build.yml' 
jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Compile all files
      uses: ArminJo/arduino-test-compile@v3
      with:
        arduino-board_fqbn: arduino:avr:uno
        required-libraries: LiquidCrystal
